### ISSUE TITLE
Shorten path to field data in blocks

### ISSUE THREAD

**Issue by mattpilott** [wp-kit/rest-kit#3]
Minor thing that would neaten things up;

This is a dot notation path im using for real:
`data.attributes.data.testimonials`

Bit weird isn't it, in lazyblock land the field data is in the top level data:
`data.testimonials`

**Comment by terence1990** [comment]
Yeah ACF likes to add this three tier data.attributes.data level. We could add it all to the top level data object, however there is a good reason to not to do this to protect the id and name properties to identify the block type and id. I know for sure we use the name property in a few projects to map to a sapper Component name i.e. lazyblocks/some-block -> SomeBlock. 

That said i think data.props.testimonials could be a good compromise. Anything we change wouldn't be backward compatible since making it backward compatible would mean we would have larger JSON body kb's sending back in the response.

You happy with with data.props.testimonials?

**Comment by mattpilott** [comment]
<img width="414" alt="Screenshot 2020-07-22 at 19 55 24" src="https://user-images.githubusercontent.com/2401925/88216656-4d562880-cc55-11ea-9f8d-aeb59225b758.png">

**Comment by mattpilott** [comment]
name is duplicate and we dont need id or mode or bid

**Comment by terence1990** [comment]
@matt3224 yeah I think we can get have four top level keys, uuid name props and innerBlocks. Then all the actual ACF keys in props. I’ll do this work in the gutenberg-object-plugin and I’m gonna move a lot of the code from GutenbergController into that too as it makes sense to consolidate it now.

It’s a major change that would break all the sites we’ve done so far with WPKit forked Gutenberg object plugin and that includes sites where we’ve used React and Lazyblocks. If we do this we have to make sure we lock the versions of the plugin in the composer.json files for those sites so it doesn’t get updated in the future.

**Comment by terence1990** [comment]
@matt3224 FYI we will need the id "block_5fs" etc. since ACF will need this to obtain the data for the block instance to resolve https://github.com/wp-kit/rest-kit/issues/2

**Comment by terence1990** [comment]
@matt3224 I've just done a release. These steps to manually upgrade will help you avoid the overwriting/data-loss issue once and for all too:

- [x] Push theme changes to git for your project (just in case)

- [x] Temporarily remove `"web/app/themes/{$name}/": ["type:wordpress-theme"]` from composer.json

- [x] Run `composer remove wp-kit/rest-kit`

- [x] Run `composer clear-cache`

- [x] Run `composer require wp-kit/rest-kit` (should install 1.0.5 - if not then perhaps set the version in composer.json to ^1.0.5, You should also see wp-kit/gutenberg-object-plugin 2.0.5)

- [x] Add back `"web/app/themes/{$name}/": ["type:wordpress-theme"]` to composer.json (Though we are adding this back, due to changes i've made to composer.json file in wp-kit/rest-kit you'll no longer have to worry about composer update breaking stuff going forward)

- [x] Remove GutenbergController from theme and update AppController and ApiController manually from master branch: https://github.com/wp-kit/rest-kit/tree/master/resources/controllers (This branch now also includes changes to hide page content)

- [x] Remove `if( defined('GUTENBERG_OBJECT_PLUGIN_CPTS') ) {invoke( 'GutenbergController', 'init' ); }` from routes.php

- [x] Add GutesObjectPlugin\Provider::class to resources/config/providers.config.php (https://github.com/wp-kit/rest-kit/blob/master/resources/config/providers.config.php#L16)

- [x] Run `npm run build`

- [x] Update a page in Wordpress admin area

- [x] See JSON for the page has `props` at top level with acf data in there with post objects and all acf data working as expected as we are now using default acf functions to get the data on request

- [x] Remember to fix the version of wp-kit/gutenberg-object-plugin in old client projects that rely on `data.attributes` to version **2.0.4** in the composer.json file for those projects. If there is no record present in composer.json it may be a sub-dependancy so add it manually to the composer.json for those projects.
