### ISSUE TITLE
Option to not output admin block markup/styles

### ISSUE THREAD

**Issue by mattpilott** [wp-kit/rest-kit#4]
Currently when you make a block the code written for the block in the backend is stored as the_content, this means it weighs down the rest response. There are certainly a couple things we can learn from lazyblocks, they give you an option to only have this markup shown in the backend (or frontend, or both)

See screen to see what im looking to avoid

![Screenshot 2020-07-22 at 16 47 09](https://user-images.githubusercontent.com/2401925/88198182-5a661e00-cc3b-11ea-8897-b48b20d7dbf6.png)

**Comment by mattpilott** [comment]
that response is **10.6kb** minified and if i remove this content it drops to **4.4kb** (i'm aware that real gains wouldn't be this drastic as we would still have some content sent back, but what we don't need is all the fluff wrapping it so the backend looks kinda like the frontend

**Comment by mattpilott** [comment]
A short term solution is obviously to wrap each block php file in a `<?php if (is_admin()) : ?>` which is maybe fine but should we have something global?

**Comment by terence1990** [comment]
Im happy to introduce default helper filters into the GutenbergController shipped with rest-kit which filter out the content from Wordpress pages rest endpoint which developers can remove if needed. Introducing it into any of the dependancies such as acf-integration or gutenberg-object-plugin would remove flexibility from users of rest-kit who want to use utilise post.content for whatever reason.

That said I think either two options are apparent; custom post and pages endpoints shipped with rest-kit into a new package wp-kit/routing or as said above in GutenbergController filtered on rest_prepare_page or something alike based on is_admin() as you’ve said.

Anything that changes default Wordpress behaviour should be in the rest-kit theme, or if handled via dependancies should be made configurable via config files in resources/config. As it’s such a small but affective change I think a basic filter in GutenbergController is the best approach so I will add this in for the next release. If you already have the code in your project and you’d like to raise a PR go ahead.

Otherwise are you happy for me to just revise GutenbergController to include some default code for pages for this? If developers need it for other post types too other than page they can simply copy and paste the filter and change the post type in the filter name.

**Comment by terence1990** [comment]
@matt3224 please add this to your ApiController, i've done a release but you should manually update the Controller:

https://github.com/wp-kit/rest-kit/blob/master/resources/controllers/ApiController.php#L22
